# Generated by Django 3.1 on 2020-08-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='languages',
            field=models.ManyToManyField(to='portfolio.Language'),
        ),
    ]
